name: first

on: [push]

jobs:

  job1:
    name: First job - ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: env | sort

  job2:
    name: Second job - windows
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
    name: Third job with dependencies
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: echo 'Hello world'