name: first

env:
  WORKFLOW_ENV: 'workflow_env'

on: [push]

jobs:

  job1:
    name: First job - ubuntu
    env:
      JOB_ENV: 'job_env'
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: env | sort
      - name: Show envs
        run: |
          echo "\$JOB_ENV: $JOB_ENV"
          echo "\$WORKFLOW_ENV: $WORKFLOW_ENV"
          echo "\$JOB_ENV: ${{ env.JOB_ENV }}"
          echo "\$WORKFLOW_ENV: ${{ env.WORKFLOW_ENV }}"
      - name: Show secrets
        run: echo "secrets.MY_SECRET ${{ secrets.MY_SECRET }}"

  job2:
    name: Second job - windows
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v4
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"

  job3:
    name: Third job with dependencies
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        run: echo 'Hello world'